import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/navbar";

import "./globals.css";
import Filters from "@/components/filters/filters";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const airports = await fetch('http://localhost:8000/airports').then(res => res.json());


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="sticky top-0 z-50 bg-white shadow">
          <Navbar />
        </div>
        <div className="flex items-start pl-4">
          <div className="flex-none max-w-sm sticky top-15">
            <Filters airportOptions={airports} />
          </div>
          <div className="grow ">
            <main className="pt-6">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
